lanuage: ruby
script: bundle exec rake --rakefile $PWD/Rakefile spec SPEC_OPTS='--format documentation'
notifications:
  email: false
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  matrix:
    - PUPPET_VERSION=2.7.23
    - PUPPET_VERSION=3.0.2
    - PUPPET_VERSION=3.1.1
    - PUPPET_VERSION=3.2.4
    - PUPPET_VERSION=3.3.2
    - PUPPET_VERSION=3.4.2
